all: light

PROJECT_SOURCEFILES += ../dag_node.c ../int-flash-common.c ../ota-main.c ../ota-common.c ../rtc-common.c
DEFINES+=PROJECT_CONF_H=\"project-conf-class-c.h\"
DEFINES+=IF_UD_LIGHT=1
DEFINES+=FAKEDEFINE=1
DEFINES+=ALT_INCOTEX_UART=1
DEFINES+=CLASS=0x0C
CONTIKI = ../..
CONTIKI_WITH_IPV6 = 1
include $(CONTIKI)/Makefile.include
include $(CONTIKI)/Makefile_git_version.include
