all: root

PROJECT_SOURCEFILES += ../root-node.c
DEFINES+=PROJECT_CONF_H=\"project-conf-class-c.h\"
DEFINES+=FAKEDEFINE=1
DEFINES+=CLASS=0x0C
PROJECTDIRS += $(VARIANT)
CONTIKI = ../..
CONTIKI_WITH_IPV6 = 1
include $(CONTIKI)/Makefile.include
include $(CONTIKI)/Makefile_git_version.include
