### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc26xx

### Include the common makefile
include $(PLATFORM_ROOT_DIR)/udboards/Makefile.udboards

CONTIKI_TARGET_DIRS += udboards/cc26xx
