deploy_ud:
	scp logic.lua router.lua version.lua root@192.168.20.187:/root/unwired_smarthome

deploy_home:
	scp logic.lua router.lua version.lua root@192.168.88.110:/root/unwired_smarthome

deploy_lan:
	scp logic.lua router.lua version.lua root@192.168.97.1:/root/unwired_smarthome
