deploy:
	scp -o ConnectTimeout=2 logic.lua root@192.168.20.187:/unwired_smarthome/ &>/dev/null  &
	scp -o ConnectTimeout=2 router.lua root@192.168.20.187:/unwired_smarthome/ &>/dev/null  &
	scp -o ConnectTimeout=2 version.lua root@192.168.20.187:/unwired_smarthome/ &>/dev/null  &
	scp -o ConnectTimeout=2 logic.lua root@192.168.88.110:/unwired_smarthome/ &>/dev/null  &
	scp -o ConnectTimeout=2 router.lua root@192.168.88.110:/unwired_smarthome/ &>/dev/null  &
	scp -o ConnectTimeout=2 version.lua root@192.168.88.1107:/unwired_smarthome/ &>/dev/null  &
	scp -o ConnectTimeout=2 logic.lua root@192.168.97.1:/unwired_smarthome/ &>/dev/null  &
	scp -o ConnectTimeout=2 router.lua root@192.168.97.1:/unwired_smarthome/ &>/dev/null  &
	scp -o ConnectTimeout=2 version.lua root@192.168.97.1:/unwired_smarthome/ &>/dev/null  &